NUTZ/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from cuentas import views as views_cuentas
from django.conf import settings
from django.views.static import serve 

urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r'^$', views_calculadora.home , name='home'),
    url(r'', include('cuentas.urls')),
    url(r'^nutricionista/', include('nutricionista.urls')),
    url(r'^paciente/', include('paciente.urls')),
    url(r'^superadmin/', include('superadmin.urls')),
    url(r'^$', views_cuentas.inicio, name='inicio' ),
    path('admin/doc/', include('django.contrib.admindocs.urls')) 

]

if settings.DEBUG:
    urlpatterns +=  [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

nutricionista/urls.py
from django.conf.urls import url
from nutricionista import views
from django.urls import path

urlpatterns = [
    url(r'^$', views.inicio_nutri, name='nutricionista'),
    url(r'^perfil/$', views.mi_perfil, name='perfil'),
    url(r'^mis-pacientes/$', views.mis_pacientes, name='pacientes'),
    url(r'^mis-pacientes/(?P<pk>\d+)/$', views.paciente_detalle, name='paciente-detalle'),
    url(r'^mis-pacientes/(?P<pk>\d+)/(?P<ficha>\w+)$', views.paciente_detalle, name='paciente-detalle-ficha'),
    url(r'^agregar-pacientes/$', views.agregar_paciente, name='pacientes-agregar'),
    url(r'^atenciones/$', views.atenciones, name='atenciones'),
    url(r'^atenciones/(?P<pk>\d+)/$', views.atencion_single, name='atencion-single'),
    url(r'^atenciones/(?P<pk>\d+)/eliminar/$', views.atencion_eliminar, name='atencion-single-eliminar'),
    url(r'^atenciones-historial/$', views.atenciones_historial, name='atenciones-historial'),
    url(r'^recomendaciones/(?P<pk>\d+)/$', views.recomendacion_paciente, name='recomendacion-paciente'),
    url(r'^recomendaciones/(?P<pk>\d+)/save/$', views.recomendacion_paciente_save, name='recomendacion-paciente'),
    url(r'^recomendaciones/(?P<pk>\d+)/crear/$', views.recomendacion_paciente_crear, name='recomendacion-paciente-crear')
    ]

paciente/urls.py
from django.conf.urls import url
from paciente import views


urlpatterns = [
    url(r'^$', views.inicio_paci, name='paciente'),
    url(r'^minuta/(?P<pk_paciente>\d+)/$', views.minuta_paciente, name='minuta-paciente'),
    url(r'^grupos-permitidos/(?P<pk_paciente>\d+)/$', views.grupos_permitidos, name='grupos-permitidos-paciente'),
    url(r'^evaluacion-nutricional/$', views.evaluacion_nutricional, name='evaluacion-nutricional'),
    url(r'^nutricionista/$', views.mi_nutricionista, name='mi-nutricionista'),    
]

nutricionista/models.py
from django.db import models
from django.apps import apps
from cuentas.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from paciente.models import Paciente
from superadmin.models import Alimento

class Nutricionista(models.Model):
    """
    Modelo ORM Nutricionista, relación uno a uno con el modelo de cuentas de la aplicación.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True, related_name='nutricionista')
    info_nutri = models.CharField(max_length=254)
    imagen = models.ImageField(null=True, blank=True, upload_to='nutricionista/')
    def __str__(self):
        return self.user.rut + " - " +self.user.email

paciente/models.py
#MODELOS
####################
from django.db import models
from cuentas.models import User
####################
#UTILS
###################
from django.contrib.postgres.fields import JSONField
from django.utils import timezone

class Paciente(models.Model):
    """
    MODELO DE BASE DE DATOS DE PACIENTE
    Este es el modelo principal de la aplicación. Los campos están divididos por ficha (Según requerimientos del cliente)
    INFORMACION GENERAL, INFORMACIÓN NUTRICIONAL, BIOQUÍMICA, TOROIDE, ANTECEDENTES ALIMENTARIOS, ETC.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, related_name='paciente') #REF: user.paciente -> Llama al único paciente del usuario
    nutricionista = models.ForeignKey('nutricionista.Nutricionista', on_delete=models.CASCADE, null=True, blank=True, related_name='pacientes') #REF: user.pacientes -> Llama a todos los pacientes del nutricionista
    def __str__(self):
        return self.user.rut + " - " +self.user.email



class AntecedentesAlimentarios(models.Model):
    paciente = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    perdida_peso = models.FloatField(null=True, blank=True, default=0)
    ganancia_peso = models.FloatField(null=True, blank=True, default=0)
    dif_deglucion = models.CharField(null=True, blank=True, default="", max_length=20)
    OPCIONES_APETITOS= (
        ('BA', 'Baja'),
        ('ME', 'Media'),
        ('AL', 'Alta'),
        )
    apetito = models.CharField(
        max_length=2,
        choices=OPCIONES_APETITOS,
        default='BA',
        )
    vomito = models.BooleanField(default=False)
    nauseas = models.BooleanField(default=False)
    diuresis = models.BooleanField(default=False)
    intolerancia_alimentaria = models.BooleanField(default=False)
    dietas = models.CharField(null=True, blank=True, default="", max_length=30)
    
    def __str__(self):
        return 'Ficha Antecedentes Alimentarios de {}'.format(self.paciente.user.get_nombre_completo)


class FichaGeneral(models.Model):
    """
    Ficha general del paciente, guarda información relacionada con antecedesntes personales
    del paciente.
    """
    paciente = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    ocupacion = models.CharField(max_length=20, blank=True, default="")
    nacionalidad = models.CharField(max_length=20, blank=True, default="")
    observacion = models.TextField(max_length=500, blank=True, default="")
    imagen = models.ImageField(null=True, blank=True, upload_to='pacientes/')

    def __str__(self):
        return 'Ficha general de {}'.format(self.paciente.user.get_nombre_completo)
        

class FichaNutricional(models.Model):
    """
    Ficha nutricional del paciente. Captura los datos que se capturan en una consulta nutricional
    convencional. Peso, talla e imc siendo las más importantes. 
    """
    paciente = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    peso = models.FloatField(null=True, blank=True, default=0)
    talla = models.FloatField(null=True, blank=True, default=0)
    imc = models.FloatField(null=True, blank=True, default=0)
    diagnostico_peso = models.CharField (null=True, blank=True, default="",max_length=20)
    cintura = models.FloatField(null=True, blank=True, default=0)
    presion_arterial = models.FloatField(null=True, blank=True, default=0)
    h_g_t = models.FloatField(null=True, blank=True, default=0)
    p_bicipital = models.FloatField(null=True, blank=True, default=0)
    p_tripicital = models.FloatField(null=True, blank=True, default=0)
    p_sub_escapular = models.FloatField(null=True, blank=True, default=0)
    p_sub_iliaco = models.FloatField(null=True, blank=True, default=0)
    c_braquial = models.FloatField(null=True, blank=True, default=0)

    def __str__(self):
        return 'Ficha Nutricional de {}'.format(self.paciente.user.get_nombre_completo)
    

class FichaBioquimica(models.Model):
    """
    La ficha bioquímica es donde la nutricionista ingresa la información de exámenes médicos.
    """
    #información bioquímica
    paciente = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    colesterol_mgdl = models.FloatField(null=True, blank=True, default=0)
    ldl_mgdl = models.FloatField(null=True, blank=True, default=0)
    tg = models.FloatField(null=True, blank=True, default=0)
    hdl = models.FloatField(null=True, blank=True, default=0)
    hemoglobina_gdll = models.FloatField(null=True, blank=True, default=0)
    hematocrito_gdll = models.FloatField(null=True, blank=True, default=0)
    leucocitos = models.FloatField(null=True, blank=True, default=0)
    plaquetas = models.FloatField(null=True, blank=True, default=0)
    v_c_m = models.FloatField(null=True, blank=True, default=0) #volumen corpuscular medio
    h_c_m = models.FloatField(null=True, blank=True, default=0) # contenido corpuscular media
    c_h_c_m = models.FloatField(null=True, blank=True, default=0) # concentracion de hemoglobina cospuscular media
    glicemia_mgdl = models.FloatField(null=True, blank=True, default=0)
    g_o_t = models.FloatField(null=True, blank=True, default=0) # transaminaza glutamicooxalacetico
    g_p_t = models.FloatField(null=True, blank=True, default=0) # transaminaza glutamicopiruvica
    f_alc = models.FloatField(null=True, blank=True, default=0) # fosfataza alcalina
    g_g_t = models.FloatField(null=True, blank=True, default=0) # gamma glutamil transpeptidaza
    bt = models.FloatField(null=True, blank=True, default=0) # bilirubina total
    bd = models.FloatField(null=True, blank=True, default=0) #bilirubina directa
    e_l_p = models.FloatField(null=True, blank=True, default=0) #electroliticos plasmaticos
    sodio = models.FloatField(null=True, blank=True, default=0) 
    potasio = models.FloatField(null=True, blank=True, default=0)
    cloro = models.FloatField(null=True, blank=True, default=0)
    creatinina = models.FloatField(null=True, blank=True, default=0)
    v_f_g = models.FloatField(null=True, blank=True, default=0) #volumen de filtrado glomerular
    r_a_c = models.FloatField(null=True, blank=True, default=0) #relacion albumina-creatininuria
    #tiroide
    tsh = models.FloatField(null=True, blank=True, default=0) # hormona estimulante tiroides
    t3 = models.FloatField(null=True, blank=True, default=0)
    t4 = models.FloatField(null=True, blank=True, default=0)
    #opcional
    t_t_g_o = models.FloatField(null=True, blank=True, default=0) #opcional y es la tolerancia a la glucosa
    glicemia_60 = models.FloatField(null=True, blank=True, default=0) #minutos
    glicemia_120 = models.FloatField(null=True, blank=True, default=0) #minutos

    def __str__(self):
            return 'Ficha Bioquímica de {}'.format(self.paciente.user.get_nombre_completo)


class CalculadoraPiramidal(models.Model):
    """
    MODELO CALCULADORA PIRAMIDAL. 
    Este modelo guarda los datos enviados desde el front-end en la pestaña de calculadora piramidal 
    y los almacena en formato JSON (campo especial de postgres que permite hacer queries sobre el json).
    """
    paciente = models.OneToOneField(Paciente, on_delete=models.CASCADE, related_name="calculadora")
    peso_a_utilizar = models.FloatField(default=0, blank=True, null=True)
    kcal_estado_nutricional = models.IntegerField(default = 0)
    total_kcal = models.FloatField(default=0, blank=True, null=True)
    vct = JSONField(blank=True, null=True)
    grupos_porciones = JSONField(blank=True, null=True)
    ultima_actualizacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return 'Calculadora de: {}'.format(self.paciente)

nutricionista/forms.py
from django import forms
from cuentas.models import User
from nutricionista.models import Nutricionista

class FormPerfil(forms.ModelForm):
    """
    Formulario para modificar los datos del nutricionsita logueado.
    Relacionado directamente con los parámetros de la base de datos.
    Hace referencia al modelo usuario.
    """
    def __init__(self, *args, **kwargs):
        """
        Constructor que inicializa los campos del ModelForm
        """
        super().__init__(*args, **kwargs)
        self.fields['rut'].widget.attrs.update({'class': 'disabled'})
        self.fields['nacimiento'].widget.attrs.update({'class': 'datepicker'})

    class Meta:
        model = User
        fields = ['rut', 'nombres', 'apellidos', 'nacimiento', 'genero']

class FormNutricionista(forms.ModelForm):
   
    class Meta:
        model = Nutricionista
        exclude = ['user']

paciente/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from cuentas.models import User
from .models import (
    AntecedentesAlimentarios,
    CalculadoraPiramidal,
    FichaBioquimica,
    FichaGeneral,
    FichaNutricional,
    Paciente
)

class FormAddPaciente(forms.ModelForm):
    """
    Formulario para agregar pacientes desde el nutricionista.
    Solo recibe los parámetros RUT e EMail que son requerimientos para ser usuario del sistema.
    """
    rut = forms.CharField(max_length=50)
    email = forms.EmailField()

    def clean_rut(self):
        """
        Valida Rut
        """
        rut = self.cleaned_data['rut']
        if User.objects.filter(rut=rut).exists():
            raise forms.ValidationError("El paciente con ese rut ya existe")
        else:
            return rut


    def clean_email(self):
        """
        Valida Rut
        """
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("El paciente con ese mail ya existe")
        else:
            return email
            
            
    class Meta:
        model = Paciente
        fields = ['rut','email']


class FormAntecedentesAlimentarios(forms.ModelForm):
    """
    Formulario para modificar la ficha de antecedentes alimentarios del paciente.
    Hace referencia al modelo paciente.
    """
    def __init__(self, *args, **kwargs):
        """
        Constructor que inicializa los campos del ModelForm
        """
        super().__init__(*args, **kwargs)


    class Meta:
        model = AntecedentesAlimentarios
        exclude = ['paciente']


class FormFichaBioquimica(forms.ModelForm):
    """
    Formulario para modificar la ficha bioquímica del paciente.
    Hace referencia al modelo paciente.
    """
    def __init__(self, *args, **kwargs):
        """
        Constructor que inicializa los campos del ModelForm
        """
        super().__init__(*args, **kwargs)

    class Meta:
        model = FichaBioquimica
        exclude = ['paciente']
        
        
class FormFichaGeneral(forms.ModelForm):
    """
    Formulario para modificar la ficha de datos generales del paciente
    Hace referencia al modelo paciente.
    """
   
    class Meta:
        model = FichaGeneral
        exclude = ['paciente']



class FormFichaNutricional(forms.ModelForm):
    """
    Formulario para modificar la ficha nutricional del paciente.
    Hace referencia al modelo paciente
    """
    def __init__(self, *args, **kwargs):
        """
        Constructor que inicializa los campos del ModelForm
        """
        super().__init__(*args, **kwargs)
        self.fields['imc'].widget.attrs.update({'readonly':'readonly'})
        self.fields['diagnostico_peso'].widget.attrs.update({'readonly':'readonly'})

    class Meta:
        model = FichaNutricional
        exclude = ['paciente']




class FormUsuario(forms.ModelForm):
    """
    Formulario para modificar los datos del nutricionsita logueado.
    Relacionado directamente con los parámetros de la base de datos.
    Hace referencia al modelo usuario.
    """
    # nacimiento = forms.DateField(input_formats=['%Y-%m-%d'])
    def __init__(self, *args, **kwargs):
        """
        Constructor que inicializa los campos del ModelForm
        """
        super().__init__(*args, **kwargs)
        self.fields['nombres'].widget.attrs.update()
        self.fields['apellidos'].widget.attrs.update()
        self.fields['nacimiento'].widget.attrs.update({'class': 'datepicker'})
        self.fields['genero'].widget.attrs.update()

    class Meta:
        model = User
        fields = ['nombres', 'apellidos', 'nacimiento', 'genero']

paciente/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from recomendacion.models import Recomendacion
from django.shortcuts import get_object_or_404
from paciente.models import Paciente
from django.http import Http404
from django.http import JsonResponse
from paciente.models import FichaNutricional
# Create your views here.

@login_required(login_url='/login-paciente/')
def inicio_paci(request):
    """
    Controlador de dashboard del paciente. Muestra información útil al paciente.
    :param request:
    :return:
    """
    if not request.user.es_paciente:
        messages.error(request, 'Usted no esta registrado como paciente')
        return HttpResponseRedirect('/login-paciente')
    # paciente = get_object_or_404(Paciente, pk=request.user.paciente.pk
    paciente = request.user.paciente
    recomendacion = Recomendacion.objects.get(paciente=paciente)
    
    return render(request, 'paciente/index.html', {'observacion': recomendacion.observacion})

def evaluacion_nutricional(request):
    paciente = request.user.paciente
    ficha_nutricional = FichaNutricional.objects.get(paciente=paciente)
    return render(request, 'paciente/evaluacion_nutricional.html', {'ficha_nutricional': ficha_nutricional})

def mi_nutricionista(request):
    paciente = request.user.paciente
    nutricionista = paciente.nutricionista
    return render(request, 'paciente/mi_nutricionista.html', {'nutricionista': nutricionista})


def minuta_paciente(request, pk_paciente):
    if Paciente.objects.filter(pk=pk_paciente).exists():
        paciente = Paciente.objects.get(pk=pk_paciente)
        recomendacion = Recomendacion.objects.get(paciente=paciente)
        return JsonResponse(recomendacion.comidas, safe=False)
    else: 
        raise Http404

def grupos_permitidos(request, pk_paciente):
    if Paciente.objects.filter(pk=pk_paciente).exists():
        paciente = Paciente.objects.get(pk=pk_paciente)
        recomendacion = Recomendacion.objects.get(paciente=paciente)
        return JsonResponse(recomendacion.grupos_permitidos, safe=False)
    else: 
        raise Http404

nutricionista/templates/nutricionista/atenciones.html
{% extends "nutricionista/base_nutricionista.html" %}
{% block activeAtenciones %} active {% endblock %}
{% block main %}
<div class="row">
    <div class="col s12">
        <h3 class="subtitulo">Listado de atenciones</h3>
        <blockquote>Listado de atenciones activo.</blockquote>
    </div>
</div>
<div class="row">
    <div class="col s12">
        {% for message in messages  %}
            {% if message.tags == 'success' %}
                <p class="green-text">{{message}}</p>
            {% else %}
                <p>{{message}}</p>
            {% endif %}
        {% endfor %} 
    </div>
</div>
<div class="container">
    <div class="row">
       <div class="col s12">
           <table class="highlight">
               <thead>
                   <tr>
                        <th>Atención en: </th>
                        <th>Fecha</th>
                        <th>Hora</th>
                        <th>Nombre</th>
                        <th>Ver detalle</th>
                   </tr>
               </thead>
               <tbody>
                    {% for atencion in atenciones  %}
                    <tr>
                        <td>{{atencion.tiempo_a_la_reserva}}</td>
                        <td>{{atencion.fecha| date:"d M Y"}}</td>
                        <td>{{atencion.hora}}</td>
                        <td>{{atencion.paciente.user.get_nombre_completo}}</td>
                        <td><a href="{% url 'atencion-single' pk=atencion.pk%}" ><i class="medium material-icons purple-text">chevron_right</i></a></td>
                    </tr>
                    {% empty %}
                        <tr>
                            <td colspan="7">No se encontraron próximas atenciones.</td>
                        </tr>
                    {% endfor %}
               </tbody>
           </table>
       </div>
    </div>
</div>
<div class="row center">
        {% if atenciones.paginator.num_pages > 1 %} 
        <ul class="pagination">
          {% if atenciones.has_previous %}
              <li class=""><a href="?page=1"><i class="material-icons">chevron_left</i></a></li>
              <li class=""><a href="?page={{ pacientes.previous_page_number }}">{{ atenciones.previous_page_number }}</a></li>
          {% else %}
              <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
          {% endif %}

          <li class="active"><a href="#!">{{ atenciones.number }}</a></li>

          {% if atenciones.has_next %}
              <li class="waves-effect"><a href="?page={{ pacientes.next_page_number }}">{{ atenciones.next_page_number }}</a></li>
              <li class="waves-effect"><a href="?page={{ pacientes.paginator.num_pages }}"><i class="material-icons">chevron_right</i></a></li>
          {% else %}
              <li class="disabled"><a href="#"><i class="material-icons">chevron_right</i></a></li>
          {% endif %}
        </ul>
        {% endif %}
</div>
{% endblock main %}

nutricionista/templates/nutricionista/paciente_ficha_bio.html
{% extends "nutricionista/base_nutricionista.html" %}
{% block activeFichaBioquimica %} active active-submenu {% endblock %}
{% block main %}
<div class="row">
    <div class="col s12">
            <div class="row sub-menu" style="padding-top:30px;">
                <div class="col s6 center">
                    <a href="{% url 'paciente-detalle-ficha' paciente.pk 'nutricional' %}" class="breadcrumb purple-text"><i class="material-icons left">navigate_before</i>Ficha Nutricional</a>
                </div>
                <div class="col s6 center">
                    <a href="{% url 'paciente-detalle-ficha' paciente.pk 'calculadora' %}" class="breadcrumb purple-text"><i class="material-icons right">navigate_next</i>Calculadora</a>
                </div>
            </div>

            <ul>
                {% for field in form %}
                    {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                {% endfor %}
            </ul>
       
    </div>
</div>
<h3 class="subtitulo">Ficha Bioquímica</h3>
<blockquote>
    En esta ficha usted debe ingresar los antecedentes bioquimicos del paciente
</blockquote>
<div class="container">
    <div class="row">
        <div class="col">
            {% for message in messages  %}
                {% if message.tags == 'success' %}
                    <p class="green-text">{{message}}</p>
                {% else %}
                    <p>{{message}}</p>
                {% endif %}
            {% endfor %}
            <form action="" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col l6">
                        <table class="bordered">
                            <thead>
                                <tr>
                                    <th colspan="3">Perfil Lipidico</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><label for="id_colesterol_mgdl">Colesterol</label>{{form.colesterol_mgdl}}</td>
                                    <td><label for="id_hdl">Colesterol HDL</label>{{form.hdl}}</td>
                                    <td><label for="id_ldl_mgdl">Colesterol LDL</label>{{form.ldl_mgdl}}</td>
                                    <td><label for="id_tg">Trigliceridos</label>{{form.tg}}</td>
                                </tr>
                            </tbody>
                        </table>
                        <table class="bordered">
                            <thead>
                                <tr>
                                    <th colspan="3">Perfil Hepatico</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><label for="id_f_alc">F. Alcalina</label>{{form.f_alc}}</td>
                                    <td><label for="id_g_g_t">GGT</label>{{form.g_g_t}}</td>
                                    <td><label for="id_g_p_t">GPT</label>{{form.g_p_t}}</td>
                                </tr>
                                <tr>
                                    <td><label for="id_g_o_t">GOT</label>{{form.g_o_t}}</td>
                                    <td><label for="id_bd">Bilirrubina Directa</label>{{form.bd}}</td>
                                    <td><label for="id_bt">Bilirrubina Indirecta</label>{{form.bt}}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col l6">
                        <table class="bordered">
                            <thead>
                                <tr>
                                    <th colspan="3">Electrocidos Plasmaticos</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><label for="id_sodio">Sodio</label>{{form.sodio}}</td>
                                    <td><label for="id_potasio">Potasio</label>{{form.potasio}}</td>
                                    <td><label for="id_cloro">Cloro</label>{{form.cloro}}</td>
                                </tr>
                            </tbody>
                        </table>
                        <table class="bordered">
                            <thead>
                                <tr>
                                    <th colspan="3">Tiroides</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><label for="id_tsh">TSH</label>{{form.tsh}}</td>
                                    <td><label for="id_t3">T3</label>{{form.t3}}</td>
                                    <td><label for="id_t4">T4</label>{{form.t4}}</td>
                                </tr>
                                <tr>
                                    <td><label for="id_v_f_g">VFG</label>{{form.v_f_g}}</td>
                                    <td><label for="id_r_a_c">RAC</label>{{form.r_a_c}}</td>
                                    <td><label for="id_creatinina">Creatinina</label>{{form.creatinina}}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col l6">
                            <table class="bordered">
                                <thead>
                                    <tr>
                                        <th colspan="4">Hemograma</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><label for="id_leucocitos">Leucocitos</label>{{form.leucocitos}}</td>
                                        <td><label for="id_e_l_p">Eritrocitos</label>{{form.e_l_p}}</td>
                                        <td><label for="hematocrito_gdll">Hematocritos</label>{{form.hematocrito_gdll}}</td>
                                        <td><label for="hemoglobina_gdll">Hemoglobina</label>{{form.hemoglobina_gdll}}</td>
                                    </tr>
                                    <tr>
                                        <td><label for="id_v_c_m">VCM</label>{{form.v_c_m}}</td>
                                        <td><label for="id_h_c_m">HCM</label>{{form.h_c_m}}</td>
                                        <td><label for="id_hdl">CHCM</label>{{form.c_h_c_m}}</td>
                                        <td><label for="id_plaquetas">Plaquetas</label>{{form.plaquetas}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>    
                            <div class="col l6">
                                <table class="bordered">
                                    <thead>
                                        <tr>
                                            <th colspan="2">Glicemia</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><label for="id_glicemia_mgdl">Glicemia</label>{{form.glicemia_mgdl}}</td>
                                            <td><label for="id_t_t_g_o">TTGO</label>{{form.t_t_g_o}}</td>
                                        </tr>
                                        <tr>
                                            <td><label for="id_glicemia_60">Glicemia 60</label>{{form.glicemia_60}}</td>
                                            <td><label for="id_glicemia_120">Glicemia 120</label>{{form.glicemia_120}}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        
                    </div>
                </div>
                    <div class="row center">
                            <button class="btn waves-effect waves-light boton" type="submit" name="action">Actualizar</button>
                    </div>  
            </form>
        </div>
    </div>
</div>
{% endblock main %}

nutricionista/templates/nutricionista/paciente_ficha_usuario.html
{% extends "nutricionista/base_nutricionista.html" %}
{% block activeFichaUsuario %} active active-submenu {% endblock %}
{% block main %}
<div class="row">
    <div class="col s12">
        <div class="row sub-menu" style="padding-top:30px;">
            <div class="col s6 center">
                <a href="{% url 'paciente-detalle' paciente.pk %}" class="breadcrumb purple-text"><span><i class="material-icons left">navigate_before</i></span> Resumen</a>
            </div>
            <div class="col s6 center">
                <a href="{% url 'paciente-detalle-ficha' paciente.pk 'general' %}" class="breadcrumb purple-text">Ficha general <span><i class="material-icons right">navigate_next</i></span> </a>
            </div>
        </div>
        <h3 class="subtitulo">Cuenta de usuario</h3>
        <blockquote>
            En esta ficha usted puede gestionar los datos de la cuenta de usuario asociada al paciente
        </blockquote>
        <ul>
            {% for field in form %}
                {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
            {% endfor %}
        </ul>     
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col s12">
            {% for message in messages  %}
                {% if message.tags == 'success' %}
                    <p class="green-text">{{message}}</p>
                {% else %}
                    <p>{{message}}</p>
                {% endif %}
            {% endfor %}
            <form name="form_usuario" action="" method="post">
                {% csrf_token %}
                {{form_usuario}}
                <div class="center">
                    <input type="submit" value="Actualizar" class="btn boton"> 
                </div>
                 
            </form>
        </div>
    </div>
</div>
{% endblock main %}